---
- name: Testing andrewrothstein.gcloud
  hosts: all
  tasks:
    - name: Installing andrewrothstein.gcloud
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Executing 'gcloud --version'
      ansible.builtin.command: sh -l -c 'gcloud --version'
      changed_when: false
      register: gcloud_version_output
    - name: Output from 'gcloud --version'
      ansible.builtin.debug:
        msg: '{{ gcloud_version_output.stdout }}'
