---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: sh -l -c 'gcloud --version'
      register: gcloud_version_output
    - name: gcloud --version
      debug:
        msg: '{{ gcloud_version_output.stdout }}'
